pipeline {
    agent any

    tools {
        jdk 'jdk'
        nodejs 'nodejs'
    }

    environment  {
        SCANNER_HOME=tool 'sonar-scanner'
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
        AWS_ECR_REPO_NAME = credentials('ECR_REPO2')
        AWS_DEFAULT_REGION = 'us-east-2'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
    }

    stages {
        stage ('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git credentialsId: 'GITHUB', url: 'https://github.com/gspvsr/3Teir-Full-Stock-NODEJS.git'
            }
        }
        stage('Sonarqube Analysis') {
                steps {
                    dir('Application-Code/frontend') {
                        withSonarQubeEnv('sonar-server') {
                            sh """
                            $SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectName=three-tier-frontend \
                            -Dsonar.projectKey=three-tier-frontend
                            """
                        }
                    }
                }
        } 
        stage('Quality Gate Check') {
            steps {
                script {
                    waitForQualityGate abortPipeline: true, credentialsId: 'sonar-creds'
                }
            }
        } 

       
        // stage('OWASP Dependency-Check Scan') {
        //     steps {
        //         dir('Application-Code/backend') {
        //             dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
        //             dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        //         }
        //     }
        // }
        stage('Trivy File Scan') {
            steps {
                dir('Application-Code/frontend') {
                    sh 'trivy fs . > trivyfs.txt'
                }
            }
        }
        stage("Docker Image Build") {
            steps {
                script {
                    dir('Application-Code/frontend') {
                            sh 'docker system prune -f'
                            sh 'docker container prune -f'
                            sh "docker build -t ${AWS_ECR_REPO_NAME} ."
                    }
                }
            }
        }
        stage("ECR Image Pushing") {
            steps {
                script {
                        sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 385554867848.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
                        sh "docker tag ${AWS_ECR_REPO_NAME} 385554867848.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}"
                        sh "docker push 385554867848.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}"

                }
            }
        }
        stage("TRIVY Image Scan") {
            steps {
                sh 'trivy image ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} > trivyimage.txt' 
            }
        }
        stage('Update Deployment file') {
        environment {
            GIT_REPO_NAME = "3Teir-Full-Stock-NODEJS"
            GIT_USER_NAME = "gspvsr"
            }
            steps {
                dir('Kubernetes-Manifests-file/frontend') {
                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        set -e

                        git config user.email "gspvsr@gmail.com"
                        git config user.name "gspvsr"

                            git fetch origin
                            git checkout master
                            git reset --hard origin/master

                            # Replace image tag with current build number
                            sed -i "s|${AWS_ECR_REPO_NAME}:.*|${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}|" deployment.yaml

                            git add deployment.yaml
                            git diff --cached --quiet || git commit -m "Update image to ${BUILD_NUMBER}"

                            # Force push safely
                            git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git master
                            '''
                        }
                    }
                }
            }

    }
}
