pipeline {
    agent any

    tools {
        jdk 'jdk'
        nodejs 'nodejs'
    }

    stages {
        stage('Init') {
            steps {
                echo 'Pipeline started'
            }
        }
    }
}
